# This describes what is deployed by this template.
description: Ryu OpenFlow controller deployed with Heat on Chameleon

# This defines the minimum Heat version required by this template.
heat_template_version: ocata

# The resources section defines what OpenStack resources are to be deployed and
# how they should be configured.
resources:
  sdx_floating_ip:
   type: OS::Nova::FloatingIP
   properties:
     pool: public

  sdx_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: sdx_floating_ip }
      server_id: { get_resource: sdx-client }



  sdx-client:
   type: OS::Nova::Server
   properties:
     name: { get_param: client_name }
     flavor: baremetal
     image: CC-CentOS7
     key_name: { get_param: key_name }
     networks:
        - network: { get_param: network_name }
     scheduler_hints: { reservation: { get_param: reservation_id } }
     user_data:
       str_replace:
         template: |
           #!/bin/bash

           WORKING_DIR=/home/cc
           {
           echo "PermitRootLogin yes" >>/etc/ssh/sshd_config
           yum install -y docker vim mlocate git maven
           systemctl start docker

           echo Start SAFE Server in Container
           docker pull yaoyj11/safeserver-v4
           docker run -i -t -d -p 7777:7777 -h safe --name safe yaoyj11/safeserver-v4
           docker exec -d safe /bin/bash -c  "cd /root/safe;export SBT_HOME=/opt/sbt-0.13.12;export SCALA_HOME=/opt/scala-2.11.8;sed -i 's/RIAKSERVER/$riak_ip/g' safe-server/src/main/resources/application.conf;./prdn.sh"

           echo Create ssh key
           ssh-keygen -t rsa -b 4096  -P "" -f "/root/.ssh/id_rsa"  -q
           cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys2
           chmod 600 ~/.ssh/authorized_keys2

           echo Git Orca
           cd $WORKING_DIR
           git clone https://github.com/RENCI-NRIG/orca5.git
           cd orca5
           mvn install


           echo Git Ahab
           cd $WORKING_DIR
           cat .ssh/id_rsa.pub >>.ssh/authorized_keys
           git clone https://github.com/RENCI-NRIG/ahab.git
           cd ahab
           mvn install

           echo Git SDX
           cd $WORKING_DIR
           git clone --single-branch -b $branch https://github.com/RENCI-NRIG/CICI-SAFE.git

           echo Build SDX
           cd ${WORKING_DIR}/CICI-SAFE/SDX-Simple/SAFE_SDX
           mvn  clean package appassembler:assemble
           
           echo Boot Script Done!
           } > ${WORKING_DIR}/boot.log 2>&1
         params:
           $sdxserver: { get_param: sdx_server }
           $plexus_ip: { get_attr: [sdx_floating_ip, ip] }
           $riak_ip: { get_param: riak_ip }
           $slice_name: { get_param: slice_name}
           $safe_keypair: {get_param: safe_keypair}
           $ip_prefix: { get_param: ip_prefix}
           $client_site: { get_param: client_site}
           $branch: { get_param: github_branch }


# The parameters section gathers configuration from the user.
parameters:
  key_name:
    type: string
    description: Name of a KeyPair to enable SSH access to the instance
    constraints:
    - custom_constraint: nova.keypair
  reservation_id:
    type: string
    description: ID of the Blazar reservation to use for launching instances.
    constraints:
    - custom_constraint: blazar.reservation
  network_name:
    type: string
    description: Name of the network used by the controller. NOT the new OpenFlow netork.
    default: sharednet1
    constraints:
    - custom_constraint: neutron.network
  client_name:
    type: string
    description: Name of the client node
    default: client1
  slice_name:
    type: string
    description: Name of the client slice
    default: c0-tri
  safe_keypair:
    type: string
    description: SAFE keypair of the client
    default: key_p10
  sdx_server:
    type: string
    description: IP/port of the sdx server
  ip_prefix:
    type: string
    description: IP prefix of the client slice
    default: 192.168.10.1/24
  client_site:
    type: string
    description: ExoGENI site of the client slice
    default: TAMU
  riak_ip:
    type: string
    description: IP of the RIAK server
  github_branch:
    type: string
    description: Github branch of code to use
    default: master

outputs:
  controller_ip:
    description: Public IP address of the NFS server
    value: { get_attr: [sdx_floating_ip, ip] }
