# This describes what is deployed by this template.
description: Ryu OpenFlow controller deployed with Heat on Chameleon

# This defines the minimum Heat version required by this template.
heat_template_version: ocata

# The resources section defines what OpenStack resources are to be deployed and
# how they should be configured.
resources:
  riak_floating_ip:
   type: OS::Nova::FloatingIP
   properties:
     pool: public

  riak_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: riak_floating_ip }
      server_id: { get_resource: riak-server }

  riak-server:
   type: OS::Nova::Server
   properties:
     name: { get_param: riak_node_name }
     flavor: baremetal
     image: CC-CentOS7
     key_name: { get_param: key_name }
     networks:
        - network: { get_param: network_name }
     scheduler_hints: { reservation: { get_param: reservation_id } }
     user_data:
       str_replace:
         template: |
           #!/bin/bash

           WORKING_DIR=/root
           {
           yum install -y docker vim mlocate
           systemctl start docker

           docker pull yaoyj11/riakimg
           docker run -i -t  -d -p 2122:2122 -p 8098:8098 -p 8087:8087 -h riakserver --name riakserver yaoyj11/riakimg
           docker exec -it riakserver sudo riak start
           docker exec -it riakserver sudo riak-admin bucket-type activate  safesets
           docker exec -it riakserver sudo riak-admin bucket-type update safesets '{"props":{"allow_mult":false}}'
           } > ${WORKING_DIR}/boot.log 2>&1
         params:
           $riak_network: { get_param: network_name }


 
# The parameters section gathers configuration from the user.
parameters:
  key_name:
    type: string
    description: Name of a KeyPair to enable SSH access to the instance
    constraints:
    - custom_constraint: nova.keypair
  reservation_id:
    type: string
    description: ID of the Blazar reservation to use for launching instances.
    constraints:
    - custom_constraint: blazar.reservation
  network_name:
    type: string
    description: Name of the network used by the controller. NOT the new OpenFlow netork.
    default: sharednet1
    constraints:
    - custom_constraint: neutron.network
  riak_node_name:
    type: string
    description: Name of the riak server
    default: riak

