# This describes what is deployed by this template.
description: Ryu OpenFlow controller deployed with Heat on Chameleon

# This defines the minimum Heat version required by this template.
heat_template_version: ocata

# The resources section defines what OpenStack resources are to be deployed and
# how they should be configured.
resources:
  sdx_floating_ip:
   type: OS::Nova::FloatingIP
   properties:
     pool: public

  sdx_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: sdx_floating_ip }
      server_id: { get_resource: sdx }



  sdx:
   type: OS::Nova::Server
   properties:
     name: { get_param: safe_node_name }
     flavor: baremetal
     image: CC-CentOS7
     key_name: { get_param: key_name }
     networks:
        - network: { get_param: network_name }
     scheduler_hints: { reservation: { get_param: reservation_id } }
     user_data:
       str_replace:
         template: |
           #!/bin/bash

           WORKING_DIR=/root
           {
           echo "PermitRootLogin yes" >>/etc/ssh/sshd_config
           yum install -y docker
           systemctl start docker

           echo Start SAFE Server in Container
           docker pull yaoyj11/safeserver-v7
           docker run -i -t -d -p 7777:7777 -h safe --name safe yaoyj11/safeserver-v7
           docker exec -d safe /bin/bash -c  "cd /root/safe;sed -i 's/RIAKSERVER/$riak_ip/g' safe-server/src/main/resources/application.conf;./prdn.sh"
           
           echo Create ssh key
           ssh-keygen -t rsa -b 4096  -P "" -f "/root/.ssh/id_rsa"  -q
           cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys2
           chmod 600 ~/.ssh/authorized_keys2


           echo Boot Script Done!
           } > ${WORKING_DIR}/boot.log 2>&1
         params:
           $riak_ip: { get_param: riak_ip }
  

# The parameters section gathers configuration from the user.
parameters:
  key_name:
    type: string
    description: Name of a KeyPair to enable SSH access to the instance
    constraints:
    - custom_constraint: nova.keypair
  reservation_id:
    type: string
    description: ID of the Blazar reservation to use for launching instances.
    constraints:
    - custom_constraint: blazar.reservation
  network_name:
    type: string
    description: Name of the network used by the controller. NOT the new OpenFlow netork.
    default: sharednet1
    constraints:
    - custom_constraint: neutron.network
  safe_node_name:
    type: string
    description: Name of the sdx server
    default: sdx
  riak_ip:
    type: string
    description: IP of the RIAK server


